#!/usr/bin/python3.10

import sys
import datetime

template = """# {date}

=  =

== Daily Tasks ==

    === Video Calls ===
        - [ ] No Video Calls

    === Today's Tasks ===
        - [ ] 
        - [ ] Shares:
            - shares need to be checked twice daily
            - [ ] check shares at open @9:30
            - [ ] check shares at close @16:30
        - [ ] Create a google and vimwiki entry

    === Shares ===
        - [ ] Bought:
            - [ ] 
        - [ ] Sold:
            - [ ] 

== Topics ==

    ===  ===

    === Topic Categories ===
        #Features - this is used to describe what features need to be added to my project
        #Bugs - this is for if I have found any bugs in my projects
        #Notes - this is for if there is a topic that I want to take notes on
        #Video Call - self explanatory
        #Hackathon - notes and description on the Hackathon that I took part in
        #Interview Prep - when I am preparing for a job Interview
        #Job Interview - when i have a job Interview
        #In Person Event - self explanatory"""
date = (datetime.date.today() if len(sys.argv) < 2
else sys.argv[1].rsplit(".",1)[0])

print(template.format(date=date))
