#!/usr/bin/python3.10

import sys
import datetime

template = """# {date}

=   =

== Used to search in dairy Index ==
    #This is an Example of titles for diary index gets placed between equals on line 3
    #Example: = Notes: This is a note =

== These are the topics for diary index ==
    #Features
    #Notes
    #Video Call
    #Hackerthon
    #Interview Prep
    #Job Interview

== Daily Tasks ==

        === Video Calls ===
            - [ ] No video calls

        === Today's notes ===
            - [ ] 

== Minutes of meetings =="""

date = (datetime.date.today() if len(sys.argv) < 2
else sys.argv[1].rsplit(".",1)[0])

print(template.format(date=date))
